name: Build and Deploy Code # every process shoul have a name
# what trigers the code to run and branches
on: [push, pull_request]

#       Staring the CI - Continous Integration

jobs:
    job1:
        env: # set up a job for env variable
            DATABASE_HOSTNAME: localhost
            DATABASE_PORT: 5432
            DATABASE_PASSWORD: password456
            DATABASE_NAME: api_project2
            DATABASE_USERNAME: postgres
            SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
            ALGORITHM: HS256
            ACCESS_TOKEN_EXPIRE_MINUTES: 60
        runs-on: windows-latest # specifying the OS
        steps:
            - name: pulling git repo # name of the actions
              uses: actions/checkout@v4 # commands from https://github.com/marketplace/actions/checkout example
            - uses: actions/setup-python@v5 #installing python
              with:
                python-version: '3.10' 
            - name: update pip
              run: python -m pip install --upgrade pip
            - name: install all dependencies #requiremnts.txt file
              run: pip install -r requirements.txt
            - name: test with pytest # to run pytest
            #to run multiple commands using | - at run command
              run: |
                pip install pytest 
                pytest


    